= Overview
:linkcss:
:stylesdir: https://pcistudio.github.io/task-processor/_/css/
:stylesheet: site.css

.Under construction
****
WARNING: This documentation is a work in progress. *If you are in a hurry just look at xref:sample:index.adoc[Sample]*
****

This project is a library designed for small businesses that are not yet ready to invest in Kafka or a message queue system, but still want a way to process tasks, keep completion records and handle retries and circuit breakers when the underlying infrastructure fails. It has a `Producer-Consumer` approach that allows you to create tasks and execute them asynchronously with the convenience that you can decide the execution time.

At the same time, it exposes metrics that can be displayed in the system of your choice to keep track of your system health. In the sample application, I chose Prometheus and Grafana.

The library is designed to be simple to use and easy to integrate into your existing projects.

At this point, the library is still in its early stages, and I am still working  the code and the documentation. I have set up a GitHub project to keep track of the features that I want to implement in next iterations.



[cols=">"]
|===
| xref:ROOT:getting-started.adoc[Next →]
|===