{
 "title": "Handlers Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "handler",
    "label": "Handlers",
    "query": {
     "query": "label_values(task_processor_handler_processing_seconds_count,handler)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Handler running",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "task_processor_handler_running", "legendFormat": "Running" },
    { "expr": "task_processor_handler_paused", "legendFormat": "Paused" },
    { "expr": "task_processor_handler_count", "legendFormat": "Total" }
   ]
  },
  { "title": "Task processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Task processed last hour by status($handler)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(exception) (floor(increase(task_processor_handler_processing_seconds_count{handler=\"$handler\"}[1h])))",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Task Processor P99.9(seconds)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, task_processor_handler_processing_seconds{handler=\"$handler\", quantile=\"0.999\"})",
     "legendFormat": "{{exception}}"
    }
   ]
  },
  {
   "title": "Task processing P99 and P999",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "task_processor_handler_processing_seconds{handler=\"$handler\",outcome!=\"error\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task processor error percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "100*sum(rate(task_processor_handler_processing_seconds_count{handler=\"$handler\",outcome=\"error\"}[1h]))/sum(rate(task_processor_handler_processing_seconds_count{handler=\"$handler\"}[1h]))",
     "legendFormat": "percentage"
    }
   ]
  },
  {
   "title": "Today exceptions view",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(task_processor_handler_processing_seconds_count{outcome=\"error\",handler=\"$handler\"}[1d]))",
     "legendFormat": "{{exception}}"
    }
   ]
  },
  {
   "title": "Today Retriable Exceptions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(task_processor_handler_processing_seconds_count{outcome=\"retry\",handler=\"$handler\"}[1d]))",
     "legendFormat": "{{exception}}"
    }
   ]
  },
  {
   "title": "Task executions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "task_processor_track_executions{handler=\"$handler\"}",
     "legendFormat": "Execution Queue"
    },
    {
     "expr": "task_processor_track_long_executions{handler=\"$handler\"}",
     "legendFormat": "Long Executions"
    }
   ]
  },
  {
   "title": "CircuitBreaker",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "task_processor_circuitbreaker_closed{handler=\"$handler\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Task polling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Polling P99.9(seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "task_processor_handler_polling_seconds{handler=\"$handler\", quantile=\"0.999\", outcome=\"success\"}",
     "legendFormat": "success"
    },
    {
     "expr": "sum without(exception) (task_processor_handler_polling_seconds{handler=\"$handler\", quantile=\"0.999\", outcome=\"error\"})",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Success polling P99 and P999",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "task_processor_handler_polling_seconds{handler=\"$handler\",outcome=\"success\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Task re-queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Tasks re-queue(last day)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(task_processor_handler_requeue_total{handler=\"$handler\"}[1d]))",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Requeue P99(seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "task_processor_handler_requeue_seconds{handler=\"$handler\",quantile=\"0.99\"}",
     "legendFormat": "{{outcome}}"
    }
   ]
  }
 ]
}